CREATE TABLE IF NOT EXISTS dropbox_accounts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    app_key VARCHAR(255) NOT NULL,
    app_secret VARCHAR(255) NOT NULL,
    access_token VARCHAR(255) NOT NULL,
    refresh_token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE dropbox_accounts 
MODIFY access_token TEXT NOT NULL,
MODIFY refresh_token TEXT NOT NULL;